version: '3'

vars:
  APP: ./cmd/vnc-recorder

tasks:
  test:
    desc: Run Go tests
    cmds:
      - go test ./...

  build:
    desc: Build local binary
    cmds:
      - mkdir -p dist
      - go build -o dist/vnc-recorder {{.APP}}

  image:
    desc: Build local Docker image
    cmds:
      - docker build -t vnc-recorder:local .

  run:
    desc: Run recorder locally
    cmds:
      - go run {{.APP}} {{.CLI_ARGS}}
